# Exercise 1

In [22]:
import numpy as np

In [23]:
def power_method(A, x, max_iter=100, tol=1e-8):

    error = 1
    iterations = 0
    eigenvalue_estimate = []
    while error > tol and iterations < max_iter:
        y = A.dot(x)
        j = np.argmax(np.abs(y))
        if y[j] == 0:
            return 0, x
        eigenvalue_estimate = y[j]
        x_update = y / eigenvalue_estimate
        error = np.linalg.norm(x - x_update, np.inf)
        x = x_update
        iterations += 1
    return eigenvalue_estimate, x/np.linalg.norm(x)

In [24]:
A = np.random.rand(4, 4)
A = (A + A.T) / 2
x = np.random.rand(4)

In [25]:
a, v = power_method(A, x)

In [26]:
print("Eigenvalue a found by Power Method:\n", a)
print("Eigenvector v found by Power Method:\n", v)
print("Multiplying A by v:\n", A.dot(v))
print("Multiplying a by v:\n", v*a)

Eigenvalue a found by Power Method:
 1.9838329419067375
Eigenvector v found by Power Method:
 [0.55127461 0.34937074 0.39055398 0.64923337]
Multiplying A by v:
 [1.09363674 0.69309319 0.77479386 1.28797055]
Multiplying a by v:
 [1.09363674 0.69309319 0.77479386 1.28797055]


In [27]:
eig_val, eig_vec = np.linalg.eig(A)
principal_index = np.argmax(np.abs(eig_val))
print("Eigenvalue found by numpy.linalg.eig:\n", eig_val[principal_index])
print("Eigenvector found by numpy.linalg.eig:\n", eig_vec[:, principal_index])

Eigenvalue found by numpy.linalg.eig:
 1.9838329431239683
Eigenvector found by numpy.linalg.eig:
 [0.55127461 0.34937074 0.39055398 0.64923337]


In [28]:
print("Divide v by numpy.linalg.eig:\n", v/eig_vec[:, principal_index])

Divide v by numpy.linalg.eig:
 [1. 1. 1. 1.]
