# Exercise 2

In [31]:
import numpy as np

In [32]:
def generate_non_singular_matrix(n):
    while True:
        A = np.random.rand(n, n)
        if np.linalg.det(A) != 0:
            return A

In [33]:
def gram_schmidt(A):

    n = A.shape[0]
    Q = np.zeros((n, n))
    R = np.zeros((n, n))

    for k in range(n):
        Q[:, k] = A[:, k]
        for i in range(k):
            R[i, k] = np.dot(Q[:, i], A[:, k])
            Q[:, k] -= R[i, k] * Q[:, i]
        Q[:, k] /= np.linalg.norm(Q[:, k])
        R[k, k] = np.dot(Q[:, k], A[:, k])

    return Q, R

In [34]:
A = generate_non_singular_matrix(4)

In [35]:
Q, R = gram_schmidt(A)

(i) $A = QR$

In [36]:
print("Generated non-singular matrix A:\n", A)
print("Q times R:\n", np.dot(Q, R))

Generated non-singular matrix A:
 [[0.92393274 0.60840575 0.73843352 0.92455517]
 [0.12412045 0.89888722 0.67539271 0.34525926]
 [0.010652   0.21833767 0.32675781 0.218846  ]
 [0.01242587 0.95626409 0.88383321 0.78412427]]
Q times R:
 [[0.92393274 0.60840575 0.73843352 0.92455517]
 [0.12412045 0.89888722 0.67539271 0.34525926]
 [0.010652   0.21833767 0.32675781 0.218846  ]
 [0.01242587 0.95626409 0.88383321 0.78412427]]


(ii) $QQ^*=I$

In [37]:
print("Q times Q_transpose:\n", np.dot(Q, np.transpose(Q)))

Q times Q_transpose:
 [[ 1.00000000e+00  3.16595955e-16 -7.23300604e-16 -2.12474835e-16]
 [ 3.16595955e-16  1.00000000e+00  1.37963791e-15  1.82917680e-15]
 [-7.23300604e-16  1.37963791e-15  1.00000000e+00  1.07922869e-15]
 [-2.12474835e-16  1.82917680e-15  1.07922869e-15  1.00000000e+00]]


(iii) $R$ is upper triangular

In [38]:
print("R:\n", R)

R:
 [[0.93237624 0.73779702 0.83716845 0.97509466]
 [0.         1.26329873 1.07277095 0.75282596]
 [0.         0.         0.19412023 0.29118305]
 [0.         0.         0.         0.18549007]]
