In [87]:
import numpy as np

In [88]:
def permutation(v):
    
    n = len(v)
    P = np.zeros((n, n))
    indices = np.argsort(-np.abs(v))
    
    for i, idx in enumerate(indices):
          P[i, idx] = 1
        
    return P

In [89]:
v = np.random.rand(4) + 1j * np.random.rand(4)

In [90]:
P = permutation(v)
print("Permuation matrix P:\n", P)

Permuation matrix P:
 [[0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]


$Pv\ $  is a vector with entries having a decreasing module

In [91]:
print("Modules of Pv:", np.abs(P.dot(v)))

Modules of Pv: [0.90640866 0.69843476 0.65765861 0.61988307]
