# Exercise 4

In [187]:
import numpy as np

In [188]:
def power_method(A, x, max_iter=100, tol=1e-8):
    error = 1
    iterations = 0
    eigenvalue_estimate = []
    while error > tol and iterations < max_iter:
        y = A.dot(x)
        j = np.argmax(np.abs(y))
        if y[j] == 0:
            return 0, x
        eigenvalue_estimate = y[j]
        x_update = y / eigenvalue_estimate
        error = np.linalg.norm(x - x_update, np.inf)
        x = x_update
        iterations += 1
    return eigenvalue_estimate, x / np.linalg.norm(x)

In [189]:
def generate_non_singular_matrix(n):
    while True:
        A = np.random.rand(n, n)
        if np.linalg.det(A) != 0:
            return A

In [190]:
def gram_schmidt(A):

    n = A.shape[0]
    Q = np.zeros((n, n))
    R = np.zeros((n, n))

    for k in range(n):
        Q[:, k] = A[:, k]
        for i in range(k):
            R[i, k] = np.dot(Q[:, i], A[:, k])
            Q[:, k] -= R[i, k] * Q[:, i]
        Q[:, k] /= np.linalg.norm(Q[:, k])
        R[k, k] = np.dot(Q[:, k], A[:, k])

    return Q, R

In [191]:
def permutation(v):
    
    n = len(v)
    P = np.zeros((n, n))
    indices = np.argsort(-np.abs(v))
    
    for i, idx in enumerate(indices):
          P[i, idx] = 1
        
    return P

In [192]:
def QR_method(A, tol=1e-8):
    error = tol + 1
    Ak = A
    Identity_matrix = np.eye(A.shape[0])
    V = np.eye(A.shape[0])
    while error > tol:
        Atmp = Ak
        epsilon = np.random.normal(loc=0, scale=1)
        Qk, Rk = gram_schmidt(Ak + epsilon * Identity_matrix)
        Ak = Rk.dot(Qk) - epsilon * Identity_matrix
        P = permutation(np.diag(Ak))
        Ak = np.linalg.inv(P).dot(Ak).dot(P)
        V = V.dot(Qk).dot(P)
        error = np.linalg.norm(np.diag(Ak) - np.diag(Atmp))
        
    return Ak, V

In [193]:
A = generate_non_singular_matrix(4)
A = (A + A.conj().T) / 2

In [194]:
Ak, V = QR_method(A)

(i) $A_k$ is diagonal when $A$ is Hermitian

In [195]:
print("Ak:\n", Ak)

Ak:
 [[ 2.54214563e+00 -2.61090516e-16  2.61996367e-16  7.49848323e-16]
 [ 3.96086190e-16  5.52013104e-01 -1.34938448e-06  1.23866487e-05]
 [-5.30575897e-22 -1.34938448e-06 -4.55093220e-01  9.21429498e-06]
 [ 8.49505247e-21  1.23866487e-05  9.21429498e-06 -2.35424509e-02]]


(ii) $VA_{k}V^*=A$

In [196]:
print("VAkV*:\n", V.dot(Ak).dot(V.conj().T))
print("A:\n", A)

VAkV*:
 [[0.98566614 0.65769813 0.28809191 0.45273866]
 [0.65769813 0.94560826 0.5514703  0.92066141]
 [0.28809191 0.5514703  0.21985299 0.74183204]
 [0.45273866 0.92066141 0.74183204 0.46439567]]
A:
 [[0.98566614 0.65769813 0.28809191 0.45273866]
 [0.65769813 0.94560826 0.5514703  0.92066141]
 [0.28809191 0.5514703  0.21985299 0.74183204]
 [0.45273866 0.92066141 0.74183204 0.46439567]]


(iii) principal eigenvector of $A$ is the first column of $V$

In [197]:
x = np.random.rand(4)
a, v = power_method(A, x)
print("the principal eigenvector of A:\n", v)
print("the first column of V:\n", V[:,0])

the principal eigenvector of A:
 [0.47626106 0.61623815 0.3677362  0.50812994]
the first column of V:
 [0.47626106 0.61623815 0.3677362  0.50812994]
