# Exercise 1

In [148]:
import numpy as np

In [149]:
def power_method(A, x, max_iter=100, tol=1e-10):

    error = 1
    iterations = 0
    eigenvalue_estimate = []
    while error > tol and iterations < max_iter:
        y = A.dot(x)
        j = np.argmax(np.abs(y))
        if y[j] == 0:
            return 0, x
        eigenvalue_estimate = y[j]
        x_update = y / eigenvalue_estimate
        error = np.linalg.norm(x - x_update, np.inf)
        x = x_update
        iterations += 1
    return eigenvalue_estimate, x/np.linalg.norm(x)

In [150]:
A = np.random.rand(4, 4)
A = (A + A.T) / 2
x = np.random.rand(4)

In [151]:
a, v = power_method(A, x)

(i) (ii) v is an eigenvector and is associated to a

In [152]:
print("Eigenvalue a found by Power Method:\n", a)
print("Eigenvector v found by Power Method:\n", v)
print("Multiplying A by v:\n", A @ v)
print("Multiplying a by v:\n", v * a)

Eigenvalue a found by Power Method:
 2.0125001379775544
Eigenvector v found by Power Method:
 [0.501005   0.38716214 0.55186776 0.54271672]
Multiplying A by v:
 [1.00827263 0.77916387 1.11063394 1.09221748]
Multiplying a by v:
 [1.00827263 0.77916387 1.11063394 1.09221748]


(iii) divide v by that of numpy.linalg.eig

In [153]:
eig_val, eig_vec = np.linalg.eig(A)
principal_index = np.argmax(np.abs(eig_val))
print("Eigenvalue found by numpy.linalg.eig:\n", eig_val[principal_index])
print("Eigenvector found by numpy.linalg.eig:\n", eig_vec[:, principal_index])
print("Divide v by numpy.linalg.eig:\n", v/eig_vec[:, principal_index])

Eigenvalue found by numpy.linalg.eig:
 2.0125001379913696
Eigenvector found by numpy.linalg.eig:
 [0.501005   0.38716214 0.55186776 0.54271672]
Divide v by numpy.linalg.eig:
 [1. 1. 1. 1.]


# Exercise 2

In [154]:
def generate_non_singular_matrix(n):
    while True:
        A = np.random.rand(n, n)
        if np.linalg.det(A) != 0:
            return A

In [155]:
def gram_schmidt(A):

    n = A.shape[0]
    Q = np.zeros((n, n))
    R = np.zeros((n, n))

    for k in range(n):
        Q[:, k] = A[:, k]
        for i in range(k):
            R[i, k] = np.dot(Q[:, i], A[:, k])
            Q[:, k] -= R[i, k] * Q[:, i]
        Q[:, k] /= np.linalg.norm(Q[:, k])
        R[k, k] = np.dot(Q[:, k], A[:, k])

    return Q, R

In [156]:
A = generate_non_singular_matrix(4)
Q, R = gram_schmidt(A)

(i) $A = QR$

In [157]:
print("Generated non-singular matrix A:\n", A)
print("Q times R:\n", Q @ R)

Generated non-singular matrix A:
 [[0.23507465 0.25454678 0.64563936 0.78999647]
 [0.1419721  0.77449956 0.32533641 0.83876396]
 [0.98121582 0.64350578 0.29254402 0.02050557]
 [0.77048608 0.03702424 0.26180276 0.95551265]]
Q times R:
 [[0.23507465 0.25454678 0.64563936 0.78999647]
 [0.1419721  0.77449956 0.32533641 0.83876396]
 [0.98121582 0.64350578 0.29254402 0.02050557]
 [0.77048608 0.03702424 0.26180276 0.95551265]]


(ii) $QQ^*=I$

In [158]:
result = Q @ Q.T
result[np.abs(result) < 1e-5] = 0
print("Q times Q_transpose:\n", result)

Q times Q_transpose:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


(iii) $R$ is upper triangular

In [159]:
print("R:\n", R)

R:
 [[1.27743863 0.64953378 0.53758069 0.83066129]
 [0.         0.81130758 0.32674207 0.44341186]
 [0.         0.         0.530154   0.84439451]
 [0.         0.         0.         0.80089325]]


# Exercise 3

In [160]:
def permutation(v):
    
    n = len(v)
    P = np.zeros((n, n))
    indices = np.argsort(-np.abs(v))
    
    for i, idx in enumerate(indices):
          P[i, idx] = 1
        
    return P

In [161]:
v = np.random.rand(4) + 1j * np.random.rand(4)
P = permutation(v)
print("Permuation matrix P:\n", P)

Permuation matrix P:
 [[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]]


$Pv\ $  is a vector with entries having a decreasing module

In [162]:
print("Modules of Pv:", np.abs(P @ v))

Modules of Pv: [1.06578827 1.02083983 0.82575243 0.25061668]


# Exercise 4

In [163]:
def QR_method(A, tol=1e-10):
    error = tol + 1
    Ak = A
    Identity_matrix = np.eye(A.shape[0])
    V = np.eye(A.shape[0])
    while error > tol:
        Atmp = Ak
        epsilon = np.random.normal(loc=0, scale=1)
        Qk, Rk = gram_schmidt(Ak + epsilon * Identity_matrix)
        Ak = Rk.dot(Qk) - epsilon * Identity_matrix
        P = permutation(np.diag(Ak))
        Ak = np.linalg.inv(P).dot(Ak).dot(P)
        V = V.dot(Qk).dot(P)
        error = np.linalg.norm(np.diag(Ak) - np.diag(Atmp))
        
    return Ak, V

In [164]:
A = generate_non_singular_matrix(4)
A = (A + A.conj().T) / 2
Ak, V = QR_method(A)

(i) $A_k$ is diagonal when $A$ is Hermitian

In [165]:
Ak[np.abs(Ak) < 1e-5] = 0
print("Ak:\n", Ak)

Ak:
 [[ 1.63901282  0.          0.          0.        ]
 [ 0.         -0.53387141  0.          0.        ]
 [ 0.          0.          0.48605248  0.        ]
 [ 0.          0.          0.         -0.13841269]]


(ii) $VA_{k}V^*=A$

In [166]:
print("VAkV*:\n", V @ Ak @ V.conj().T)
print("A:\n", A)

VAkV*:
 [[0.67673652 0.34284658 0.51707867 0.11210056]
 [0.34284658 0.02800676 0.62935936 0.32636545]
 [0.51707867 0.62935936 0.24553904 0.57230193]
 [0.11210056 0.32636545 0.57230193 0.50249886]]
A:
 [[0.6767373  0.34284873 0.51707613 0.11210087]
 [0.34284873 0.02800646 0.62935924 0.32636348]
 [0.51707613 0.62935924 0.24553971 0.57230404]
 [0.11210087 0.32636348 0.57230404 0.50249772]]


(iii) principal eigenvector of $A$ is the first column of $V$

In [167]:
x = np.random.rand(4)
a, v = power_method(A, x)
print("the principal eigenvector of A:\n", v)
print("the first column of V:\n", V[:,0])

the principal eigenvector of A:
 [0.51695636 0.42940349 0.57660014 0.46465152]
the first column of V:
 [0.51695636 0.42940349 0.57660014 0.46465152]


# Problem 1

In [175]:
A = np.array([
    [0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0.5],
    [1, 0, 0, 0, 0],
    [0, 0.5, 0, 0, 0.5],
    [0, 0.5, 0, 1, 0]    
])
for i in range(10):
    x = np.random.rand(5)
    a, v = power_method(A, x)
    print("trial", i+1)
    print("Multiplying A by v:\n", A @ v)
    print("Multiplying a by v:\n", v * a)
    print("\n")

trial 1
Multiplying A by v:
 [0.42581806 0.21261641 0.70066925 0.31892461 0.42523281]
Multiplying a by v:
 [0.70066925 0.21261641 0.42581806 0.31892461 0.42523281]


trial 2
Multiplying A by v:
 [0.26864036 0.15989962 0.86166419 0.23984942 0.31979923]
Multiplying a by v:
 [0.86166419 0.15989962 0.26864036 0.23984942 0.31979923]


trial 3
Multiplying A by v:
 [0.35496405 0.27938811 0.55505143 0.41908216 0.55877621]
Multiplying a by v:
 [0.55505143 0.27938811 0.35496405 0.41908216 0.55877621]


trial 4
Multiplying A by v:
 [0.03999917 0.30809354 0.5569724  0.46214031 0.61618708]
Multiplying a by v:
 [0.5569724  0.30809354 0.03999917 0.46214031 0.61618708]


trial 5
Multiplying A by v:
 [0.6913413  0.1354854  0.62366984 0.2032281  0.2709708 ]
Multiplying a by v:
 [0.62366984 0.1354854  0.6913413  0.2032281  0.2709708 ]


trial 6
Multiplying A by v:
 [0.45968694 0.22766873 0.64257162 0.3415031  0.45533746]
Multiplying a by v:
 [0.64257162 0.22766873 0.45968694 0.3415031  0.45533746]


tria

Observation: only the second, fourth, and fifth entries are correspondent.
v is not the real eigenvector.

# Problem 2

In [176]:
x1 = np.array([0, 0.57, 0, 0.57, 0.57])
x2 = np.array([0.7, 0, 0.7, 0, 0])
a1, v1 = power_method(A, x1)
a2, v2 = power_method(A, x2)
print("Multiplying A by v1:\n", A @ v1)
print("Multiplying a1 by v1:\n", v1 * a1)
print("\n")
print("Multiplying A by v2:\n", A @ v2)
print("Multiplying a1 by v2:\n", v2 * a2)

Multiplying A by v1:
 [0.         0.37139068 0.         0.55708601 0.74278135]
Multiplying a1 by v1:
 [0.         0.37139068 0.         0.55708601 0.74278135]


Multiplying A by v2:
 [0.70710678 0.         0.70710678 0.         0.        ]
Multiplying a1 by v2:
 [0.70710678 0.         0.70710678 0.         0.        ]


# Problem 3

# Problem 4

In [177]:
alpha = 0.1
A_prime = (1 - alpha) * A + 0.2 * alpha * np.ones(A.shape)
x = np.random.rand(5)
a_prime, v_prime = power_method(A_prime, x)
print("Multiplying A' by v':\n", A_prime @ v_prime)
print("Multiplying a' by v':\n", v_prime * a_prime)

Multiplying A' by v':
 [0.43884212 0.30264747 0.43884286 0.43883878 0.57503009]
Multiplying a' by v':
 [0.43884333 0.30264749 0.43884252 0.4388388  0.57503011]


# Problem 5

In [215]:
Ak, V = QR_method(A)
product = V @ Ak @ V.conj().T
product[np.abs(product) < 1e-5] = 0
Ak[np.abs(Ak) < 1e-5] = 0
print("Ak:\n", Ak)
print("V:\n", V)
print("VAkV*:\n", product)

Ak:
 [[ 1.          0.          0.          0.40825195  0.15160975]
 [ 0.          1.          0.          0.          0.        ]
 [ 0.          0.         -1.          0.          0.        ]
 [ 0.          0.          0.         -0.50001346 -0.55708601]
 [ 0.          0.          0.          0.         -0.49998654]]
V:
 [[ 0.         -0.70710678 -0.70710678  0.          0.        ]
 [-0.37139068  0.          0.         -0.83389799  0.40826843]
 [ 0.         -0.70710678  0.70710678  0.          0.        ]
 [-0.55708601  0.          0.         -0.15163933 -0.81649292]
 [-0.74278135  0.          0.          0.53067849  0.40823547]]
VAkV*:
 [[0.  0.  1.  0.  0. ]
 [0.  0.  0.  0.  0.5]
 [1.  0.  0.  0.  0. ]
 [0.  0.5 0.  0.  0.5]
 [0.  0.5 0.  1.  0. ]]


In [214]:
eig_val, eig_vec = np.linalg.eig(A)
product = (eig_vec @ np.diag(eig_val) @ np.linalg.inv(eig_vec)).real
# product = (eig_vec @ np.diag(eig_val) @ eig_vec.conj().T).real
product[np.abs(product) < 1e-5] = 0
print("eigenvalue using numpy.linaly.eig:\n", (eig_val).real)
eig_vec = (eig_vec).real
eig_vec[np.abs(eig_vec) < 1e-5] = 0
print("eigenvector using numpy.linaly.eig:\n", eig_vec)
print("reconstruction using numpy.linaly.eig:\n", product)

eigenvalue using numpy.linaly.eig:
 [ 1.  -1.   1.  -0.5 -0.5]
eigenvector using numpy.linaly.eig:
 [[ 0.70710678  0.70710678  0.          0.          0.        ]
 [ 0.          0.         -0.37139068  0.70710678  0.70710678]
 [ 0.70710678 -0.70710678  0.          0.          0.        ]
 [ 0.          0.         -0.55708601  0.          0.        ]
 [ 0.          0.         -0.74278135 -0.70710678 -0.70710678]]
reconstruction using numpy.linaly.eig:
 [[0.  0.  1.  0.  0. ]
 [0.  0.  0.  0.  0.5]
 [1.  0.  0.  0.  0. ]
 [0.  0.5 0.  0.  0.5]
 [0.  0.5 0.  1.  0. ]]
