# Exercise 1

In [360]:
import numpy as np

In [361]:
def power_method(A, x, max_iter=100, tol=1e-10):

    error = 1
    iterations = 0
    eigenvalue_estimate = []
    while error > tol and iterations < max_iter:
        y = A.dot(x)
        j = np.argmax(np.abs(y))
        if y[j] == 0:
            return 0, x
        eigenvalue_estimate = y[j]
        x_update = y / eigenvalue_estimate
        error = np.linalg.norm(x - x_update, np.inf)
        x = x_update
        iterations += 1
    return eigenvalue_estimate, x/np.linalg.norm(x)

In [362]:
A = np.random.rand(4, 4)
A = (A + A.T) / 2
x = np.random.rand(4)
a, v = power_method(A, x)

(i) (ii) v is an eigenvector and is associated to a

In [364]:
print("Eigenvalue a found by Power Method:\n", a)
print("Eigenvector v found by Power Method:\n", v)
print("Multiplying A by v:\n", A @ v)
print("Multiplying a by v:\n", v * a)

Eigenvalue a found by Power Method:
 2.262509892318244
Eigenvector v found by Power Method:
 [0.40887132 0.57797605 0.36653646 0.60367124]
Multiplying A by v:
 [0.9250754  1.30767652 0.82929236 1.36581215]
Multiplying a by v:
 [0.9250754  1.30767652 0.82929236 1.36581215]


(iii) divide v by that of numpy.linalg.eig

In [365]:
eig_val, eig_vec = np.linalg.eig(A)
principal_index = np.argmax(np.abs(eig_val))
print("Eigenvalue found by numpy.linalg.eig:\n", eig_val[principal_index])
print("Eigenvector found by numpy.linalg.eig:\n", eig_vec[:, principal_index])
print("Divide v by numpy.linalg.eig:\n", v/eig_vec[:, principal_index])

Eigenvalue found by numpy.linalg.eig:
 2.2625098922876474
Eigenvector found by numpy.linalg.eig:
 [0.40887132 0.57797605 0.36653646 0.60367124]
Divide v by numpy.linalg.eig:
 [1. 1. 1. 1.]


# Exercise 2

In [374]:
def generate_non_singular_matrix(n):
    while True:
        A = np.random.rand(n, n)
        if np.linalg.det(A) != 0:
            return A

In [375]:
def gram_schmidt(A):

    n = A.shape[0]
    Q = np.zeros((n, n))
    R = np.zeros((n, n))

    for k in range(n):
        Q[:, k] = A[:, k]
        for i in range(k):
            R[i, k] = np.dot(Q[:, i], A[:, k])
            Q[:, k] -= R[i, k] * Q[:, i]
        Q[:, k] /= np.linalg.norm(Q[:, k])
        R[k, k] = np.dot(Q[:, k], A[:, k])

    return Q, R

In [376]:
A = generate_non_singular_matrix(4)
Q, R = gram_schmidt(A)

(i) $A = QR$

In [377]:
print("Generated non-singular matrix A:\n", A)
print("Q times R:\n", Q @ R)

Generated non-singular matrix A:
 [[0.9987338  0.33688933 0.60774038 0.76808714]
 [0.63422074 0.98900917 0.43223689 0.23439069]
 [0.01726823 0.93837312 0.0101805  0.07019707]
 [0.81339758 0.79845591 0.94263026 0.96469238]]
Q times R:
 [[0.9987338  0.33688933 0.60774038 0.76808714]
 [0.63422074 0.98900917 0.43223689 0.23439069]
 [0.01726823 0.93837312 0.0101805  0.07019707]
 [0.81339758 0.79845591 0.94263026 0.96469238]]


(ii) $QQ^*=I$

In [378]:
Q_times_Q_transpose = Q @ Q.T
Q_times_Q_transpose_thresholded = np.where(abs(Q_times_Q_transpose) < 1e-5, 0, Q_times_Q_transpose)
print("Q times Q_transpose:\n", Q_times_Q_transpose_thresholded)

Q times Q_transpose:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


(iii) $R$ is upper triangular

In [379]:
print("R:\n", R)

R:
 [[ 1.43583389  1.13479633  1.14777443  1.18513754]
 [ 0.          1.14975945  0.07996376 -0.01581153]
 [ 0.          0.          0.34792557  0.3425058 ]
 [ 0.          0.          0.          0.24154637]]


# Exercise 3

In [381]:
def permutation(v):
    
    n = len(v)
    P = np.zeros((n, n))
    indices = np.argsort(-np.abs(v))
    
    for i, idx in enumerate(indices):
          P[i, idx] = 1
        
    return P

In [382]:
v = np.random.rand(4) + 1j * np.random.rand(4)
P = permutation(v)
print("Permuation matrix P:\n", P)

Permuation matrix P:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]


$Pv\ $  is a vector with entries having a decreasing module

In [383]:
print("Modules of Pv:", np.abs(P @ v))

Modules of Pv: [0.89694243 0.7341278  0.4047902  0.3797649 ]


# Exercise 4

In [385]:
def QR_method(A, tol=1e-10):
    error = tol + 1
    Ak = A
    Identity_matrix = np.eye(A.shape[0])
    V = np.eye(A.shape[0])
    while error > tol:
        Atmp = Ak
        epsilon = np.random.normal(loc=0, scale=1)
        Qk, Rk = gram_schmidt(Ak + epsilon * Identity_matrix)
        Ak = Rk.dot(Qk) - epsilon * Identity_matrix
        P = permutation(np.diag(Ak))
        Ak = np.linalg.inv(P).dot(Ak).dot(P)
        V = V.dot(Qk).dot(P)
        error = np.linalg.norm(np.diag(Ak) - np.diag(Atmp))
        
    return Ak, V

In [386]:
A = generate_non_singular_matrix(4)
A = (A + A.conj().T) / 2
Ak, V = QR_method(A)

(i) $A_k$ is diagonal when $A$ is Hermitian

In [387]:
Ak_thresholded = np.where(abs(Ak) < 1e-5, 0, Ak)
print("Ak:\n", Ak_thresholded)

Ak:
 [[ 2.58989233  0.          0.          0.        ]
 [ 0.          0.51040572  0.          0.        ]
 [ 0.          0.          0.22549862  0.        ]
 [ 0.          0.          0.         -0.18494509]]


(ii) $VA_{k}V^*=A$

In [391]:
print("VAkV*:\n", V @ Ak @ V.conj().T)
print("A:\n", A)

VAkV*:
 [[0.74044664 0.56463019 0.88795242 0.49156154]
 [0.56463019 0.82751306 0.60974302 0.59643588]
 [0.88795242 0.60974302 0.67777264 0.4508956 ]
 [0.49156154 0.59643588 0.4508956  0.89511925]]
A:
 [[0.74044664 0.56463019 0.88795242 0.49156154]
 [0.56463019 0.82751306 0.60974302 0.59643588]
 [0.88795242 0.60974302 0.67777264 0.4508956 ]
 [0.49156154 0.59643588 0.4508956  0.89511925]]


(iii) principal eigenvector of $A$ is the first column of $V$

In [392]:
x = np.random.rand(4)
a, v = power_method(A, x)
print("the principal eigenvector of A:\n", v)
print("the first column of V:\n", V[:,0])

the principal eigenvector of A:
 [0.52179555 0.5010719  0.51145389 0.46375778]
the first column of V:
 [0.52179555 0.5010719  0.51145389 0.46375777]


# Problem 1

In [394]:
A = np.array([
    [0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0.5],
    [1, 0, 0, 0, 0],
    [0, 0.5, 0, 0, 0.5],
    [0, 0.5, 0, 1, 0]    
])
for i in range(10):
    x = np.random.rand(5)
    a, v = power_method(A, x)
    print("trial", i+1)
    print("Multiplying A by v:\n", A @ v)
    print("Multiplying a by v:\n", v * a)

trial 1
Multiplying A by v:
 [0.1575628  0.29186503 0.59798101 0.43779755 0.58373006]
Multiplying a by v:
 [0.59798101 0.29186503 0.1575628  0.43779755 0.58373006]
trial 2
Multiplying A by v:
 [0.49435705 0.24877377 0.55400388 0.37316065 0.49754754]
Multiplying a by v:
 [0.55400388 0.24877377 0.49435705 0.37316065 0.49754754]
trial 3
Multiplying A by v:
 [0.59345787 0.26295434 0.38276184 0.39443151 0.52590867]
Multiplying a by v:
 [0.38276184 0.26295434 0.59345787 0.39443151 0.52590867]
trial 4
Multiplying A by v:
 [0.70151651 0.26461083 0.01541505 0.39691625 0.52922166]
Multiplying a by v:
 [0.01541505 0.26461083 0.70151651 0.39691625 0.52922166]
trial 5
Multiplying A by v:
 [0.66415064 0.26492375 0.22375346 0.39738563 0.52984751]
Multiplying a by v:
 [0.22375346 0.26492375 0.66415064 0.39738563 0.52984751]
trial 6
Multiplying A by v:
 [0.17560335 0.30331046 0.54971222 0.45496569 0.60662091]
Multiplying a by v:
 [0.54971222 0.30331046 0.17560335 0.45496569 0.60662091]
trial 7
Multiply

Observation: only the second, fourth, and fifth entries of $Av$ and $av$ are correspondent.
v is not the real eigenvector.

# Problem 2

In [472]:
x1 = np.array([0, 0.57, 0, 0.57, 0.57])
x2 = np.array([0.7, 0, 0.7, 0, 0])
a1, v1 = power_method(A, x1)
a2, v2 = power_method(A, x2)
print("eigenvalue a1 by initial guess x1:\n", a1)
print("eigenvector v1 by initial guess x1:\n", v1)
print("eigenvalue a1 by initial guess x1:\n", a1)
print("eigenvector v2 by initial guess x2:\n", v2)
print("Multiplying A by v1:\n", A @ v1)
print("Multiplying a1 by v1:\n", v1 * a1)
print("Multiplying A by v2:\n", A @ v2)
print("Multiplying a1 by v2:\n", v2 * a2)

eigenvalue a1 by initial guess x1:
 0.9999999999563443
eigenvector v1 by initial guess x1:
 [0.         0.37139068 0.         0.55708601 0.74278135]
eigenvalue a1 by initial guess x1:
 0.9999999999563443
eigenvector v2 by initial guess x2:
 [0.70710678 0.         0.70710678 0.         0.        ]
Multiplying A by v1:
 [0.         0.37139068 0.         0.55708601 0.74278135]
Multiplying a1 by v1:
 [0.         0.37139068 0.         0.55708601 0.74278135]
Multiplying A by v2:
 [0.70710678 0.         0.70710678 0.         0.        ]
Multiplying a1 by v2:
 [0.70710678 0.         0.70710678 0.         0.        ]


$v1$ is the eigenvector by initial guess $x1$. $v2$ is the eigenvector by initial guess $x2$.
$v1$ and $v2$ are two different eigenvectors associated to eigenvalue 1. 

# Problem 3

$A$ is column stochastic, so $\rho(A)=1$.
$A$ is not stricly positive as $A$ has some zero entries.
Therefore, $A$ has multiple eigenvalue which equals 1.
Power method is effective when there is only one principal eigenvalue.

# Problem 4

In [460]:
alpha = 0.1
A_prime = (1 - alpha) * A + 0.2 * alpha * np.ones(A.shape)
x = np.random.rand(5)
a_prime, v_prime = power_method(A_prime, x)
print("eigenvalue of pertubated A:\n", a_prime)
print("eigenvector of pertubated A:\n", v_prime)
print("Multiplying A' by v':\n", A_prime @ v_prime)
print("Multiplying a' by v':\n", v_prime * a_prime)

eigenvalue of pertubated A:
 1.0000000998996932
eigenvector of pertubated A:
 [0.43884271 0.30264816 0.43883887 0.43883983 0.57503149]
Multiplying A' by v':
 [0.43883901 0.30264819 0.43884246 0.43883986 0.57503154]
Multiplying a' by v':
 [0.43884276 0.30264819 0.43883892 0.43883987 0.57503154]


This pertubation make $A'$ a strictly positve matrix. Therefore, the problem can be solved by power method.

# Problem 5

In [398]:
Ak, V = QR_method(A)
product = V @ Ak @ V.conj().T
Ak_thresholded = np.where(abs(Ak) < 1e-5, 0, Ak)
product_thresholded = np.where(abs(product) < 1e-5, 0, product)
print("Ak:\n", Ak_thresholded)
print("V:\n", V)
print("VAkV*:\n", product_thresholded)

Ak:
 [[ 1.          0.          0.          0.          0.        ]
 [ 0.         -1.          0.          0.          0.        ]
 [ 0.          0.          1.          0.40825231  0.15160879]
 [ 0.          0.          0.         -0.50001477 -0.55708601]
 [ 0.          0.          0.          0.         -0.49998523]]
V:
 [[-0.70710678  0.70710678  0.          0.          0.        ]
 [ 0.          0.          0.37139068  0.83389703 -0.4082704 ]
 [-0.70710678 -0.70710678  0.          0.          0.        ]
 [ 0.          0.          0.55708601  0.15164125  0.81649256]
 [ 0.          0.          0.74278135 -0.53067945 -0.40823422]]
VAkV*:
 [[0.  0.  1.  0.  0. ]
 [0.  0.  0.  0.  0.5]
 [1.  0.  0.  0.  0. ]
 [0.  0.5 0.  0.  0.5]
 [0.  0.5 0.  1.  0. ]]


In [403]:
eig_val, eig_vec = np.linalg.eig(A)
product = (eig_vec @ np.diag(eig_val) @ np.linalg.inv(eig_vec)).real
product_thresholded = np.where(abs(product) < 1e-5, 0, product)
eig_vec = eig_vec.real
eig_vec_thresholded = np.where(abs(eig_vec) < 1e-5, 0, eig_vec)
print("eigenvalue using numpy.linaly.eig:\n", eig_val.real)
print("eigenvector using numpy.linaly.eig:\n", eig_vec_thresholded)
print("reconstruction using numpy.linaly.eig:\n", product_thresholded)

eigenvalue using numpy.linaly.eig:
 [ 1.  -1.   1.  -0.5 -0.5]
eigenvector using numpy.linaly.eig:
 [[ 0.70710678  0.70710678  0.          0.          0.        ]
 [ 0.          0.         -0.37139068  0.70710678  0.70710678]
 [ 0.70710678 -0.70710678  0.          0.          0.        ]
 [ 0.          0.         -0.55708601  0.          0.        ]
 [ 0.          0.         -0.74278135 -0.70710678 -0.70710678]]
reconstruction using numpy.linaly.eig:
 [[0.  0.  1.  0.  0. ]
 [0.  0.  0.  0.  0.5]
 [1.  0.  0.  0.  0. ]
 [0.  0.5 0.  0.  0.5]
 [0.  0.5 0.  1.  0. ]]


Both methods can diagonalize A correctly.