# Exercise 1

In [73]:
import numpy as np

In [74]:
def power_method(A, x, max_iter=100, tol=1e-10):

    error = 1
    iterations = 0
    eigenvalue_estimate = []
    while error > tol and iterations < max_iter:
        y = A.dot(x)
        j = np.argmax(np.abs(y))
        if y[j] == 0:
            return 0, x
        eigenvalue_estimate = y[j]
        x_update = y / eigenvalue_estimate
        error = np.linalg.norm(x - x_update, np.inf)
        x = x_update
        iterations += 1
    return eigenvalue_estimate, x/np.linalg.norm(x)

In [75]:
A = np.random.rand(4, 4)
A = (A + A.T) / 2
x = np.random.rand(4)

In [76]:
a, v = power_method(A, x)

(i) (ii) v is an eigenvector and is associated to a

In [77]:
print("Eigenvalue a found by Power Method:\n", a)
print("Eigenvector v found by Power Method:\n", v)
print("Multiplying A by v:\n", A @ v)
print("Multiplying a by v:\n", v * a)

Eigenvalue a found by Power Method:
 1.909689269472612
Eigenvector v found by Power Method:
 [0.28182492 0.5539178  0.55796024 0.5499365 ]
Multiplying A by v:
 [0.53819803 1.05781088 1.06553069 1.05020783]
Multiplying a by v:
 [0.53819803 1.05781088 1.06553069 1.05020783]


(iii) divide v by that of numpy.linalg.eig

In [78]:
eig_val, eig_vec = np.linalg.eig(A)
principal_index = np.argmax(np.abs(eig_val))
print("Eigenvalue found by numpy.linalg.eig:\n", eig_val[principal_index])
print("Eigenvector found by numpy.linalg.eig:\n", eig_vec[:, principal_index])
print("Divide v by numpy.linalg.eig:\n", v/eig_vec[:, principal_index])

Eigenvalue found by numpy.linalg.eig:
 1.909689269418103
Eigenvector found by numpy.linalg.eig:
 [0.28182492 0.5539178  0.55796024 0.5499365 ]
Divide v by numpy.linalg.eig:
 [1. 1. 1. 1.]


# Exercise 2

In [79]:
def generate_non_singular_matrix(n):
    while True:
        A = np.random.rand(n, n)
        if np.linalg.det(A) != 0:
            return A

In [80]:
def gram_schmidt(A):

    n = A.shape[0]
    Q = np.zeros((n, n))
    R = np.zeros((n, n))

    for k in range(n):
        Q[:, k] = A[:, k]
        for i in range(k):
            R[i, k] = np.dot(Q[:, i], A[:, k])
            Q[:, k] -= R[i, k] * Q[:, i]
        Q[:, k] /= np.linalg.norm(Q[:, k])
        R[k, k] = np.dot(Q[:, k], A[:, k])

    return Q, R

In [81]:
A = generate_non_singular_matrix(4)
Q, R = gram_schmidt(A)

(i) $A = QR$

In [82]:
print("Generated non-singular matrix A:\n", A)
print("Q times R:\n", Q @ R)

Generated non-singular matrix A:
 [[0.09094167 0.21684859 0.44142593 0.46488173]
 [0.48305431 0.43368414 0.77789304 0.98328662]
 [0.38614472 0.38352616 0.77473543 0.80929171]
 [0.40171273 0.51085415 0.20028689 0.24339337]]
Q times R:
 [[0.09094167 0.21684859 0.44142593 0.46488173]
 [0.48305431 0.43368414 0.77789304 0.98328662]
 [0.38614472 0.38352616 0.77473543 0.80929171]
 [0.40171273 0.51085415 0.20028689 0.24339337]]


(ii) $QQ^*=I$

In [83]:
result = Q @ Q.T
result[np.abs(result) < 1e-5] = 0
print("Q times Q_transpose:\n", result)

Q times Q_transpose:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


(iii) $R$ is upper triangular

In [84]:
print("R:\n", R)

R:
 [[ 0.74302942  0.78398885  1.0706526   1.24831652]
 [ 0.          0.16891121 -0.04054529 -0.09885916]
 [ 0.          0.          0.54070632  0.56466238]
 [ 0.          0.          0.          0.10124296]]


# Exercise 3

In [85]:
def permutation(v):
    
    n = len(v)
    P = np.zeros((n, n))
    indices = np.argsort(-np.abs(v))
    
    for i, idx in enumerate(indices):
          P[i, idx] = 1
        
    return P

In [86]:
v = np.random.rand(4) + 1j * np.random.rand(4)
P = permutation(v)
print("Permuation matrix P:\n", P)

Permuation matrix P:
 [[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


$Pv\ $  is a vector with entries having a decreasing module

In [87]:
print("Modules of Pv:", np.abs(P @ v))

Modules of Pv: [1.11593452 0.8584823  0.42472586 0.35283141]


# Exercise 4

In [88]:
def QR_method(A, tol=1e-10):
    error = tol + 1
    Ak = A
    Identity_matrix = np.eye(A.shape[0])
    V = np.eye(A.shape[0])
    while error > tol:
        Atmp = Ak
        epsilon = np.random.normal(loc=0, scale=1)
        Qk, Rk = gram_schmidt(Ak + epsilon * Identity_matrix)
        Ak = Rk.dot(Qk) - epsilon * Identity_matrix
        P = permutation(np.diag(Ak))
        Ak = np.linalg.inv(P).dot(Ak).dot(P)
        V = V.dot(Qk).dot(P)
        error = np.linalg.norm(np.diag(Ak) - np.diag(Atmp))
        
    return Ak, V

In [89]:
A = generate_non_singular_matrix(4)
A = (A + A.conj().T) / 2
Ak, V = QR_method(A)

(i) $A_k$ is diagonal when $A$ is Hermitian

In [90]:
Ak[np.abs(Ak) < 1e-5] = 0
print("Ak:\n", Ak)

Ak:
 [[ 2.21654046  0.          0.          0.        ]
 [ 0.         -0.36553831  0.          0.        ]
 [ 0.          0.          0.32850079  0.        ]
 [ 0.          0.          0.         -0.21931638]]


(ii) $VA_{k}V^*=A$

In [91]:
print("VAkV*:\n", V @ Ak @ V.conj().T)
print("A:\n", A)

VAkV*:
 [[0.14147773 0.56999875 0.50381739 0.42347344]
 [0.56999875 0.97954964 0.55505031 0.52878452]
 [0.50381739 0.55505031 0.67672938 0.72363469]
 [0.42347344 0.52878452 0.72363469 0.16242981]]
A:
 [[0.14147768 0.57000072 0.50381572 0.42347283]
 [0.57000072 0.97954847 0.55505013 0.52878463]
 [0.50381572 0.55505013 0.67673055 0.72363496]
 [0.42347283 0.52878463 0.72363496 0.16242985]]


(iii) principal eigenvector of $A$ is the first column of $V$

In [92]:
x = np.random.rand(4)
a, v = power_method(A, x)
print("the principal eigenvector of A:\n", v)
print("the first column of V:\n", V[:,0])

the principal eigenvector of A:
 [0.38679565 0.60665802 0.54659702 0.4284704 ]
the first column of V:
 [-0.38679565 -0.60665802 -0.54659702 -0.4284704 ]


# Problem 1

In [93]:
A = np.array([
    [0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0.5],
    [1, 0, 0, 0, 0],
    [0, 0.5, 0, 0, 0.5],
    [0, 0.5, 0, 1, 0]    
])
for i in range(10):
    x = np.random.rand(5)
    a, v = power_method(A, x)
    print("trial", i+1)
    print("Multiplying A by v:\n", A @ v)
    print("Multiplying a by v:\n", v * a)
    print("\n")

trial 1
Multiplying A by v:
 [0.11600209 0.35429471 0.27656671 0.53144206 0.70858942]
Multiplying a by v:
 [0.27656671 0.35429471 0.11600209 0.53144206 0.70858942]


trial 2
Multiplying A by v:
 [0.4406296  0.33191974 0.08430821 0.49787961 0.66383948]
Multiplying a by v:
 [0.08430821 0.33191974 0.4406296  0.49787961 0.66383948]


trial 3
Multiplying A by v:
 [0.46252126 0.2229282  0.65251127 0.33439231 0.44585641]
Multiplying a by v:
 [0.65251127 0.2229282  0.46252126 0.33439231 0.44585641]


trial 4
Multiplying A by v:
 [0.35441272 0.27656819 0.56554345 0.41485228 0.55313638]
Multiplying a by v:
 [0.56554345 0.27656819 0.35441272 0.41485228 0.55313638]


trial 5
Multiplying A by v:
 [0.70168337 0.26330864 0.07062237 0.39496295 0.52661727]
Multiplying a by v:
 [0.07062237 0.26330864 0.70168337 0.39496295 0.52661727]


trial 6
Multiplying A by v:
 [0.13736618 0.33394128 0.41549233 0.50091193 0.66788257]
Multiplying a by v:
 [0.41549233 0.33394128 0.13736618 0.50091193 0.66788257]


tria

Observation: only the second, fourth, and fifth entries are correspondent.
v is not the real eigenvector.

# Problem 2

In [94]:
x1 = np.array([0, 0.57, 0, 0.57, 0.57])
x2 = np.array([0.7, 0, 0.7, 0, 0])
a1, v1 = power_method(A, x1)
a2, v2 = power_method(A, x2)
print("Multiplying A by v1:\n", A.dot(v1))
print("Multiplying a1 by v1:\n", v1 * a1)
print("\n")
print("Multiplying A by v2:\n", A.dot(v2))
print("Multiplying a1 by v2:\n", v2 * a2)

Multiplying A by v1:
 [0.         0.37139068 0.         0.55708601 0.74278135]
Multiplying a1 by v1:
 [0.         0.37139068 0.         0.55708601 0.74278135]


Multiplying A by v2:
 [0.70710678 0.         0.70710678 0.         0.        ]
Multiplying a1 by v2:
 [0.70710678 0.         0.70710678 0.         0.        ]


# Problem 3

# Problem 4

In [95]:
alpha = 0.1
A_prime = (1 - alpha) * A + 0.2 * alpha * np.ones(A.shape)
x = np.random.rand(5)
a_prime, v_prime = power_method(A_prime, x)
print("Multiplying A' by v':\n", A_prime.dot(v_prime))
print("Multiplying a' by v':\n", v_prime * a_prime)

Multiplying A' by v':
 [0.43883259 0.30264765 0.43885149 0.43883905 0.57503046]
Multiplying a' by v':
 [0.43885289 0.30264767 0.43883189 0.43883907 0.57503048]


# Problem 5

In [96]:
Ak, V = QR_method(A)
print("Ak:\n", Ak)

Ak:
 [[ 1.00000000e+000  0.00000000e+000  0.00000000e+000 -4.08258684e-001
  -1.51591615e-001]
 [ 0.00000000e+000  1.00000000e+000  8.88308235e-014  0.00000000e+000
   0.00000000e+000]
 [ 0.00000000e+000  8.90079750e-201 -1.00000000e+000  0.00000000e+000
   0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 -5.00038192e-001
  -5.57086012e-001]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  3.77974296e-010
  -4.99961801e-001]]
