# Page Rank

In [14]:
import numpy as np

In [15]:
def power_method(A, x, max_iter=100, tol=1e-8):

    error = 1
    iterations = 0
    eigenvalue_estimate = []
    while error > tol and iterations < max_iter:
        y = A.dot(x)
        j = np.argmax(np.abs(y))
        if y[j] == 0:
            return 0, x
        eigenvalue_estimate = y[j]
        x_update = y / eigenvalue_estimate
        error = np.linalg.norm(x - x_update, np.inf)
        x = x_update
        iterations += 1
    return eigenvalue_estimate, x/np.linalg.norm(x)

In [16]:
def gram_schmidt(A):
    n = A.shape[0]
    Q = np.zeros((n, n))
    R = np.zeros((n, n))

    for k in range(n):
        Q[:, k] = A[:, k]
        for i in range(k):
            R[i, k] = np.dot(Q[:, i], A[:, k])
            Q[:, k] -= R[i, k] * Q[:, i]
        Q[:, k] /= np.linalg.norm(Q[:, k])
        R[k, k] = np.dot(Q[:, k], A[:, k])

    return Q, R

In [17]:
def permutation(v):
    n = len(v)
    P = np.zeros((n, n))
    indices = np.argsort(-np.abs(v))

    for i, idx in enumerate(indices):
        P[i, idx] = 1

    return P

In [18]:
def QR_method(A, tol=1e-8):
    error = tol + 1
    Ak = A
    Identity_matrix = np.eye(A.shape[0])
    V = np.eye(A.shape[0])
    while error > tol:
        Atmp = Ak
        epsilon = np.random.normal(loc=0, scale=1)
        Qk, Rk = gram_schmidt(Ak + epsilon * Identity_matrix)
        Ak = Rk.dot(Qk) - epsilon * Identity_matrix
        P = permutation(np.diag(Ak))
        Ak = np.linalg.inv(P).dot(Ak).dot(P)
        V = V.dot(Qk).dot(P)
        error = np.linalg.norm(np.diag(Ak) - np.diag(Atmp))
        
    return Ak, V

In [19]:
A = np.array([
    [0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0.5],
    [1, 0, 0, 0, 0],
    [0, 0.5, 0, 0, 0.5],
    [0, 0.5, 0, 1, 0]    
])

# Problem 1

In [20]:
for i in range(10):
    x = np.random.rand(5)
    a, v = power_method(A, x)
    print("trial", i+1)
    print("Multiplying A by v:\n", A.dot(v))
    print("Multiplying a by v:\n", v * a)
    print("\n")

trial 1
Multiplying A by v:
 [0.11930363 0.27535489 0.66035548 0.41303233 0.55070978]
Multiplying a by v:
 [0.66035548 0.27535489 0.11930363 0.41303233 0.55070978]


trial 2
Multiplying A by v:
 [0.26383975 0.35236845 0.17379018 0.52855268 0.7047369 ]
Multiplying a by v:
 [0.17379018 0.35236845 0.26383975 0.52855268 0.7047369 ]


trial 3
Multiplying A by v:
 [0.30921904 0.35313033 0.0173529  0.52969549 0.70626066]
Multiplying a by v:
 [0.0173529  0.35313033 0.30921904 0.52969549 0.70626066]


trial 4
Multiplying A by v:
 [0.032889   0.22532594 0.79424361 0.33798891 0.45065188]
Multiplying a by v:
 [0.79424361 0.22532594 0.032889   0.33798891 0.45065188]


trial 5
Multiplying A by v:
 [0.65202471 0.25639868 0.31344335 0.38459802 0.51279735]
Multiplying a by v:
 [0.31344335 0.25639868 0.65202471 0.38459802 0.51279735]


trial 6
Multiplying A by v:
 [0.53444766 0.31278771 0.07108869 0.46918156 0.62557542]
Multiplying a by v:
 [0.07108869 0.31278771 0.53444766 0.46918156 0.62557542]


tria

Observation: only the second, fourth, and fifth entries are correspondent

# Problem 2

In [21]:
x1 = np.array([0, 0.57, 0, 0.57, 0.57])
x2 = np.array([0.7, 0, 0.7, 0, 0])
a1, v1 = power_method(A, x1)
a2, v2 = power_method(A, x2)

In [22]:
print("Multiplying A by v1:\n", A.dot(v1))
print("Multiplying a1 by v1:\n", v1 * a1)
print("\n")
print("Multiplying A by v2:\n", A.dot(v2))
print("Multiplying a1 by v2:\n", v2 * a2)

Multiplying A by v1:
 [0.         0.37139068 0.         0.55708601 0.74278135]
Multiplying a1 by v1:
 [0.         0.37139068 0.         0.55708602 0.74278136]


Multiplying A by v2:
 [0.70710678 0.         0.70710678 0.         0.        ]
Multiplying a1 by v2:
 [0.70710678 0.         0.70710678 0.         0.        ]


# Problem 3

leave it blank...

# Problem 4

In [23]:
alpha = np.random.rand()
A_prime = (1 - alpha) * A + 0.2 * alpha * np.ones(A.shape)
x = np.random.rand(5)

In [24]:
a_prime, v_prime = power_method(A_prime, x)
print("Multiplying A' by v':\n", A_prime.dot(v_prime))
print("Multiplying a' by v':\n", v_prime * a_prime)

Multiplying A by v':
 [0.43937275 0.30754387 0.43937281 0.43937281 0.57120174]
Multiplying a' by v':
 [0.43937281 0.30754387 0.43937274 0.4393728  0.57120174]


what difference?

# Problem 5

In [27]:
Ak, V = QR_method(A)
print("Ak:\n", Ak)

Ak:
 [[-1.00000000e+00  0.00000000e+00  1.80281749e-14  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00 -4.08282134e-01
  -1.51528450e-01]
 [ 1.54762324e-23  0.00000000e+00  1.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00 -5.00124388e-01
  -5.57085987e-01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.77877943e-08
  -4.99875613e-01]]


In [28]:
eig_val, eig_vec = np.linalg.eig(A)
print("diagonalization of A using numpy.linaly.eig:\n", eig_vec @ np.diag(eig_val) @ np.linalg.inv(eig_vec))

diagonalization of A using numpy.linaly.eig:
 [[ 1.01465364e-17+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   1.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00+0.00000000e+00j  6.05135015e-16+7.91605811e-10j
   0.00000000e+00+0.00000000e+00j  5.15287719e-16-2.66122606e-10j
   5.00000000e-01+2.46049678e-10j]
 [ 1.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   1.01465364e-17+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00+0.00000000e+00j  5.00000000e-01-1.50086023e-09j
   0.00000000e+00+0.00000000e+00j  1.66533454e-16+3.00172047e-09j
   5.00000000e-01-1.50086023e-09j]
 [ 0.00000000e+00+0.00000000e+00j  5.00000000e-01-2.72268825e-09j
   0.00000000e+00+0.00000000e+00j  1.00000000e+00+5.99093264e-09j
  -5.27355937e-16-3.10845469e-09j]]
