# Page Rank

In [14]:
import numpy as np

In [15]:
def power_method(A, x, max_iter=100, tol=1e-8):

    error = 1
    iterations = 0
    eigenvalue_estimate = []
    while error > tol and iterations < max_iter:
        y = A.dot(x)
        j = np.argmax(np.abs(y))
        if y[j] == 0:
            return 0, x
        eigenvalue_estimate = y[j]
        x_update = y / eigenvalue_estimate
        error = np.linalg.norm(x - x_update, np.inf)
        x = x_update
        iterations += 1
    return eigenvalue_estimate, x/np.linalg.norm(x)

In [16]:
def gram_schmidt(A):
    n = A.shape[0]
    Q = np.zeros((n, n))
    R = np.zeros((n, n))

    for k in range(n):
        Q[:, k] = A[:, k]
        for i in range(k):
            R[i, k] = np.dot(Q[:, i], A[:, k])
            Q[:, k] -= R[i, k] * Q[:, i]
        Q[:, k] /= np.linalg.norm(Q[:, k])
        R[k, k] = np.dot(Q[:, k], A[:, k])

    return Q, R

In [17]:
def permutation(v):
    n = len(v)
    P = np.zeros((n, n))
    indices = np.argsort(-np.abs(v))

    for i, idx in enumerate(indices):
        P[i, idx] = 1

    return P

In [18]:
def QR_method(A, tol=1e-8):
    error = tol + 1
    Ak = A
    Identity_matrix = np.eye(A.shape[0])
    V = np.eye(A.shape[0])
    while error > tol:
        Atmp = Ak
        epsilon = np.random.normal(loc=0, scale=1)
        Qk, Rk = gram_schmidt(Ak + epsilon * Identity_matrix)
        Ak = Rk.dot(Qk) - epsilon * Identity_matrix
        P = permutation(np.diag(Ak))
        Ak = np.linalg.inv(P).dot(Ak).dot(P)
        V = V.dot(Qk).dot(P)
        error = np.linalg.norm(np.diag(Ak) - np.diag(Atmp))
        
    return Ak, V

In [19]:
A = np.array([
    [0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0.5],
    [1, 0, 0, 0, 0],
    [0, 0.5, 0, 0, 0.5],
    [0, 0.5, 0, 1, 0]    
])

# Problem 1

In [20]:
for i in range(10):
    x = np.random.rand(5)
    a, v = power_method(A, x)
    print("trial", i+1)
    print("Multiplying A by v:\n", A.dot(v))
    print("Multiplying a by v:\n", v * a)
    print("\n")

trial 1
Multiplying A by v:
 [0.56028376 0.30623813 0.07851195 0.45935719 0.61247625]
Multiplying a by v:
 [0.07851195 0.30623813 0.56028376 0.45935719 0.61247625]


trial 2
Multiplying A by v:
 [0.87808793 0.16663653 0.16626945 0.24995479 0.33327306]
Multiplying a by v:
 [0.16626945 0.16663653 0.87808793 0.24995479 0.33327306]


trial 3
Multiplying A by v:
 [0.10778541 0.322861   0.48233592 0.48429149 0.64572199]
Multiplying a by v:
 [0.48233592 0.322861   0.10778541 0.48429149 0.64572199]


trial 4
Multiplying A by v:
 [0.50081711 0.31993018 0.08429786 0.47989528 0.63986037]
Multiplying a by v:
 [0.08429786 0.31993018 0.50081711 0.47989528 0.63986037]


trial 5
Multiplying A by v:
 [0.6834713  0.20916299 0.46441963 0.31374449 0.41832598]
Multiplying a by v:
 [0.46441963 0.20916299 0.6834713  0.31374449 0.41832598]


trial 6
Multiplying A by v:
 [0.44308104 0.299043   0.39412623 0.44856451 0.59808601]
Multiplying a by v:
 [0.39412623 0.299043   0.44308104 0.44856451 0.59808601]


tria

Observation: only the second, fourth, and fifth entries are correspondent

# Problem 2

In [21]:
x1 = np.array([0, 0.57, 0, 0.57, 0.57])
x2 = np.array([0.7, 0, 0.7, 0, 0])
a1, v1 = power_method(A, x1)
a2, v2 = power_method(A, x2)

In [22]:
print("Multiplying A by v1:\n", A.dot(v1))
print("Multiplying a1 by v1:\n", v1 * a1)
print("\n")
print("Multiplying A by v2:\n", A.dot(v2))
print("Multiplying a1 by v2:\n", v2 * a2)

Multiplying A by v1:
 [0.         0.37139068 0.         0.55708601 0.74278135]
Multiplying a1 by v1:
 [0.         0.37139068 0.         0.55708602 0.74278136]


Multiplying A by v2:
 [0.70710678 0.         0.70710678 0.         0.        ]
Multiplying a1 by v2:
 [0.70710678 0.         0.70710678 0.         0.        ]


# Problem 3

leave it blank...

# Problem 4

In [23]:
alpha = np.random.rand()
A_prime = (1 - alpha) * A + 0.2 * alpha * np.ones(A.shape)
x = np.random.rand(5)

In [24]:
a_prime, v_prime = power_method(A_prime, x)
print("Multiplying A' by v':\n", A_prime.dot(v_prime))
print("Multiplying a' by v':\n", v_prime * a_prime)

Multiplying A' by v':
 [0.44326585 0.34951905 0.44326585 0.44326585 0.53701265]
Multiplying a' by v':
 [0.44326585 0.34951905 0.44326585 0.44326585 0.53701265]


what difference?

# Problem 5

In [25]:
Ak, V = QR_method(A)
print("Ak:\n", Ak)

Ak:
 [[ 1.00000000e+000  0.00000000e+000  1.76620237e-015  0.00000000e+000
   0.00000000e+000]
 [ 0.00000000e+000  1.00000000e+000  0.00000000e+000 -4.08295477e-001
   1.51492496e-001]
 [ 7.65440156e-163  0.00000000e+000 -1.00000000e+000  0.00000000e+000
   0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 -5.00173445e-001
   5.57085961e-001]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000 -5.40016980e-008
  -4.99826555e-001]]


In [26]:
eig_val, eig_vec = np.linalg.eig(A)
print("diagonalization of A using numpy.linaly.eig:\n", eig_vec @ np.diag(eig_val) @ np.linalg.inv(eig_vec))

diagonalization of A using numpy.linaly.eig:
 [[ 0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   1.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00+0.00000000e+00j  5.36098377e-16-1.12046577e-25j
   0.00000000e+00+0.00000000e+00j  3.84970966e-16+2.24093155e-25j
   5.00000000e-01-1.12046577e-25j]
 [ 1.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00+0.00000000e+00j  5.00000000e-01-1.76768623e-09j
   0.00000000e+00+0.00000000e+00j  2.22044605e-16+3.53537245e-09j
   5.00000000e-01-1.76768623e-09j]
 [ 0.00000000e+00+0.00000000e+00j  5.00000000e-01-2.42326536e-09j
   0.00000000e+00+0.00000000e+00j  1.00000000e+00+4.84653072e-09j
  -4.44089210e-16-2.42326536e-09j]]
