In [6]:
import numpy as np

def power_method(A, x, max_iter=1000, tol=1e-6):

  x = x / np.linalg.norm(x)  # Normalize initial guess
  for i in range(max_iter):
    x_new = A @ x
    if np.linalg.norm(x_new) < tol:
      return 0, x / np.linal.normg(x) # normalize eigenvector
    x = x_new / np.linalg.norm(x_new,ord=np.inf)
  return np.linalg.norm(x_new,ord=np.inf), x / np.linalg.norm(x) # normalize eigenvector

In [7]:
# Test on a random symmetric 4x4 real matrix
np.random.seed(4)
A = np.random.rand(4, 4)
A = (A + A.T) / 2  # Making A symmetric
print("Random symmetric matrix A:")
print(A)

Random symmetric matrix A:
[[0.96702984 0.62248054 0.61283336 0.78890461]
 [0.62248054 0.2160895  0.70553299 0.49481547]
 [0.61283336 0.70553299 0.77938292 0.18076366]
 [0.78890461 0.49481547 0.18076366 0.59733394]]


(i) your $v$ is indeed an eigenvector;

(ii) your $v$ is indeed associated to your $a$;

In [8]:
# Using Power Method
x = np.random.rand(4)  # Initial guess for eigenvector
a, v = power_method(A, x)
print("\nEigenvalue found by Power Method:", a)
print("Eigenvector found by Power Method:", v)


Eigenvalue found by Power Method: 2.4052223720279455
Eigenvector found by Power Method: [0.62966403 0.43106512 0.47333028 0.44007332]


In [9]:
# Using numpy.linalg.eig for comparison
eigvals, eigvecs = np.linalg.eig(A)
principal_idx = np.argmax(np.abs(eigvals))
print("\nEigenvalue found by numpy.linalg.eig:", eigvals[principal_idx])
print("Eigenvector found by numpy.linalg.eig:", eigvecs[:, principal_idx])

# Comparing eigenvectors
print("\nComparison of eigenvectors:")
print("Normalized eigenvector (Power Method):", v)
print("Normalized eigenvector (numpy.linalg.eig):", eigvecs[:, principal_idx])


Eigenvalue found by numpy.linalg.eig: 2.4052223720279424
Eigenvector found by numpy.linalg.eig: [0.62966403 0.43106512 0.47333028 0.44007332]

Comparison of eigenvectors:
Normalized eigenvector (Power Method): [0.62966403 0.43106512 0.47333028 0.44007332]
Normalized eigenvector (numpy.linalg.eig): [0.62966403 0.43106512 0.47333028 0.44007332]


(iii) divide your $v$ by that of $numpy.linalg.eig$

In [10]:
# Comparing eigenvectors
print("\nComparison of eigenvectors:")
print("Normalized eigenvector (Power Method):", v)
print("Normalized eigenvector (numpy.linalg.eig):", eigvecs[:, principal_idx])


Comparison of eigenvectors:
Normalized eigenvector (Power Method): [0.62966403 0.43106512 0.47333028 0.44007332]
Normalized eigenvector (numpy.linalg.eig): [0.62966403 0.43106512 0.47333028 0.44007332]
