In [47]:
import numpy as np

def power_method(A, x, max_iter=1000, tol=1e-6):
  """
  Power Method to find principal eigenvalue and eigenvector of a matrix A.
  Parameters:
    A (ndarray): Matrix for which eigenvalue and eigenvector are to be found.
    x (ndarray): Initial guess for the eigenvector.
    max_iter (int): Maximum number of iterations (default=1000).
    tol (float): Tolerance for convergence (default=1e-6).
  Returns:
    a (float): Principal eigenvalue of A.
    v (ndarray): Eigenvector corresponding to the principal eigenvalue.
  """
  x = x / np.linalg.norm(x)  # Normalize initial guess
  for i in range(max_iter):
    x_new = A @ x
    if np.linalg.norm(x_new) < tol:
      return 0, x / np.linal.normg(x) # normalize eigenvector
    x = x_new / np.linalg.norm(x_new,ord=np.inf)
  return np.linalg.norm(x_new,ord=np.inf), x / np.linalg.norm(x) # normalize eigenvector

In [48]:
# Test on a random symmetric 4x4 real matrix
np.random.seed(42)
A = np.random.rand(4, 4)
A = (A + A.T) / 2  # Making A symmetric
print("Random symmetric matrix A:")
print(A)

Random symmetric matrix A:
[[0.37454012 0.55336647 0.66655448 0.71555056]
 [0.55336647 0.15599452 0.38307809 0.53925763]
 [0.66655448 0.38307809 0.02058449 0.57586741]
 [0.71555056 0.53925763 0.57586741 0.18340451]]


(i) your $v$ is indeed an eigenvector;

(ii) your $v$ is indeed associated to your $a$;

In [49]:
# Using Power Method
x = np.random.rand(4)  # Initial guess for eigenvector
a, v = power_method(A, x)
print("\nEigenvalue found by Power Method:", a)
print("Eigenvector found by Power Method:", v)


Eigenvalue found by Power Method: 1.9344170523556687
Eigenvector found by Power Method: [0.58375278 0.43543757 0.44681529 0.5195988 ]


In [50]:
# Using numpy.linalg.eig for comparison
eigvals, eigvecs = np.linalg.eig(A)
principal_idx = np.argmax(np.abs(eigvals))
print("\nEigenvalue found by numpy.linalg.eig:", eigvals[principal_idx])
print("Eigenvector found by numpy.linalg.eig:", eigvecs[:, principal_idx])

# Comparing eigenvectors
print("\nComparison of eigenvectors:")
print("Normalized eigenvector (Power Method):", v)
print("Normalized eigenvector (numpy.linalg.eig):", eigvecs[:, principal_idx])


Eigenvalue found by numpy.linalg.eig: 1.9344170523556699
Eigenvector found by numpy.linalg.eig: [0.58375278 0.43543757 0.44681529 0.5195988 ]

Comparison of eigenvectors:
Normalized eigenvector (Power Method): [0.58375278 0.43543757 0.44681529 0.5195988 ]
Normalized eigenvector (numpy.linalg.eig): [0.58375278 0.43543757 0.44681529 0.5195988 ]


(iii) divide your $v$ by that of $numpy.linalg.eig$

In [51]:
# Comparing eigenvectors
print("\nComparison of eigenvectors:")
print("Normalized eigenvector (Power Method):", v)
print("Normalized eigenvector (numpy.linalg.eig):", eigvecs[:, principal_idx])


Comparison of eigenvectors:
Normalized eigenvector (Power Method): [0.58375278 0.43543757 0.44681529 0.5195988 ]
Normalized eigenvector (numpy.linalg.eig): [0.58375278 0.43543757 0.44681529 0.5195988 ]
