In [82]:
import numpy as np

# np.set_printoptions(precision=3)

def permutation(v):
    """
    Constructs a permutation matrix from a complex vector following the order of the modulus of the entries.
    Parameters:
        v (ndarray): Complex vector.
    Returns:
        P (ndarray): Permutation matrix.
    """
    # Sort indices of v based on the modulus of entries
    sorted_indices = np.argsort(abs(v))[::-1]

    # Create permutation matrix
    n = len(v)
    P = np.zeros((n, n))
    for i, idx in enumerate(sorted_indices):
      P[i, idx] = 1

    return P

In [83]:
# Example input
v = np.random.rand(5) + 1j * np.random.rand(5) # v is a complex vector
print("Input complex vector:", v)

Input complex vector: [0.79 +0.319j 0.778+0.334j 0.878+0.191j 0.757+0.237j 0.672+0.061j]


In [84]:
# Construct permutation matrix
P = permutation(v)
print("\nPermutation matrix:")
print(P)


Permutation matrix:
[[0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [85]:
# Verify that Pv has entries with decreasing modulus
Pv = P @ v
print("\nPv (resulting vector after applying permutation):", Pv)
print("\nModulus of Pv entries (should be in decreasing order):", np.abs(Pv))
is_sorted_desc = np.all(np.diff(np.abs(Pv)) <= 0)
print("\nModulus of Pv entries is in decreasing order:", is_sorted_desc)


Pv (resulting vector after applying permutation): [0.878+0.191j 0.79 +0.319j 0.778+0.334j 0.757+0.237j 0.672+0.061j]

Modulus of Pv entries (should be in decreasing order): [0.898 0.852 0.847 0.793 0.674]

Modulus of Pv entries is in decreasing order: True
